### ISSUE TITLE
Can't change font-size

### ISSUE THREAD

**Issue by WilsonNet** [rsimmons/voracious#37]
Default .srt font-size is too small for me, can't find a way to change it on settings.

**Comment by WilsonNet** [comment]
A workaround that I found is to change the font size in \Voracious\resources\app\stactic\css\main.*.css

```css
.Player-text-chunks {
  position: absolute;
  bottom: 60px;
  left: 0;
  right: 0;
}
.Player-text-chunk-outer {
  background: rgba(0, 0, 0, 0);
}
.Player-text-chunk-inner {
  color: #fff;
  text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000,
    1px 1px 0 #000, 0 0 5px #000;
  font-size: 2rem;
  text-align: center;
  overflow: hidden;
  padding: 0.3em 0.5em;
  margin: 10px auto;
}

```
These classes are responsible for the subtitles.

**Comment by fxmarty** [comment]
This file is not accessible using Linux.

**Comment by MosaabMuhammed** [comment]
For Linux users, to make any changes in AppImage file, you need to navigate to Voracious location path, extract it using the following command:
```
./Voracious-0.6.0-linux-x86_64.AppImage --appimage-extract 
```
You will see that a folder created called **squashfs-root**. In that folder you have the internal files of the Voracious.AppImage and you can make any changes to suit your standards.
You can access the file mentioned by @WilsonNet and change the font as you like.

To run the program, with the new changes, simply you find file called **AppRun** inside your **squashfs-root** folder, simply run it, and your changes will be there!

If you want to turn it again into an AppImage file with your changes, make sure to install **appimagetool**, then run the following command:
```
ARCH=x86_64 ./appimagetool-x86_64.AppImage squashfs-root
```
NOTE: make sure **appimagetool** in the same directory, or write its path in the previous command.

**Comment by tomholub** [comment]
Excellent!

To leave everything as is but have gigantic subs, I just added this to the bottom of the css file:

```css
.Player-text-chunk-inner {
  font-size: 3rem;
}
```
